# Generated by Django 6.0.2 on 2026-03-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="original_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
