# Generated by Django 6.0.2 on 2026-03-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_invoice_assigned_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="service_end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when service/session ended (on finalising invoice)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="service_start_time",
            field=models.DateTimeField(
                blank=True, help_text="Time when service/session started", null=True
            ),
        ),
    ]
