"""
Django settings for vora_backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-n3r4lf2j!+v-*)meeklz9ojwl7$31sqc9d%+i1-cbvm3&hrls@"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "vora.thehps.in",
    "api.vora.thehps.in",
    "145.223.18.5",
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    'unfold',  # Unfold admin theme
    'unfold.contrib.filters',  # Optional: Unfold filters
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'user_auth',
    'tenant',
    'inventory',
    'customers',
    'billing',
    'appointments',
    'memberships',
    'packages',
    'marketing',
    'experience',
    'reports',
    'support',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "vora_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                'django.template.context_processors.debug',
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "vora_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "voradb",
        "USER": "vora",
        "PASSWORD": "vora123",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8081",
    "http://localhost:5173", # Vite dev server
    "http://localhost:3000", # Common React dev port
    "https://vora.thehps.in",
    "https://api.vora.thehps.in",
    "http://145.223.18.5",
]

CSRF_TRUSTED_ORIGINS = [
    "https://vora.thehps.in",
    "https://api.vora.thehps.in",
]

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Unfold Admin Configuration
from django.templatetags.static import static
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "Vora Super Admin",
    "SITE_HEADER": "Vora Network Manager",
    "SITE_URL": "/",
    "DASHBOARD_CALLBACK": "tenant.admin.dashboard_callback",
    "STYLES": [
        lambda request: static("css/admin_vora.css"),
    ],
    "COLORS": {
        "primary": {
            "50": "255 241 242",
            "100": "255 228 230",
            "200": "254 205 211",
            "300": "253 164 175",
            "400": "251 113 133",
            "500": "244 63 94",   # Rose 500
            "600": "225 29 72",
            "700": "190 18 60",
            "800": "159 18 57",
            "900": "136 19 55",
            "950": "76 5 25",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Network Management"),
                "separator": True,
                "items": [
                    {
                        "title": _("Salons"),
                        "icon": "store",
                        "link": lambda request: reverse("admin:tenant_tenant_changelist"),
                    },
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": lambda request: reverse("admin:auth_user_changelist"),
                    },
                ],
            },
            {
                "title": _("Business Operations"),
                "separator": True,
                "items": [
                    {
                        "title": _("Appointments"),
                        "icon": "calendar_month",
                        "link": lambda request: reverse("admin:appointments_appointment_changelist"),
                    },
                    {
                        "title": _("Services"),
                        "icon": "content_cut",
                        "link": lambda request: reverse("admin:appointments_service_changelist"),
                    },
                ],
            },
            {
                "title": _("Billing & Finance"),
                "separator": True,
                "items": [
                    {
                        "title": _("Invoices"),
                        "icon": "receipt_long",
                        "link": lambda request: reverse("admin:billing_invoice_changelist"),
                    },
                ],
            },
            {
                "title": _("Inventory Management"),
                "separator": True,
                "items": [
                    {
                        "title": _("Products"),
                        "icon": "inventory_2",
                        "link": lambda request: reverse("admin:inventory_product_changelist"),
                    },
                    {
                        "title": _("Suppliers"),
                        "icon": "local_shipping",
                        "link": lambda request: reverse("admin:inventory_supplier_changelist"),
                    },
                    {
                        "title": _("Stock History"),
                        "icon": "history",
                        "link": lambda request: reverse("admin:inventory_stocktransaction_changelist"),
                    },
                ],
            },
            {
                "title": _("CRM & Experience"),
                "separator": True,
                "items": [
                    {
                        "title": _("Customers"),
                        "icon": "group",
                        "link": lambda request: reverse("admin:customers_customer_changelist"),
                    },
                    {
                        "title": _("Staff Members"),
                        "icon": "badge",
                        "link": lambda request: reverse("admin:experience_staff_changelist"),
                    },
                    {
                        "title": _("Reviews"),
                        "icon": "reviews",
                        "link": lambda request: reverse("admin:experience_review_changelist"),
                    },
                ],
            },
            {
                "title": _("Loyalty & Packages"),
                "separator": True,
                "items": [
                    {
                        "title": _("Membership Plans"),
                        "icon": "card_membership",
                        "link": lambda request: reverse("admin:memberships_membershipplan_changelist"),
                    },
                    {
                        "title": _("Member Subscriptions"),
                        "icon": "subscriptions",
                        "link": lambda request: reverse("admin:memberships_subscription_changelist"),
                    },
                    {
                        "title": _("Service Packages"),
                        "icon": "featured_play_list",
                        "link": lambda request: reverse("admin:packages_package_changelist"),
                    },
                ],
            },
            {
                "title": _("Marketing"),
                "separator": True,
                "items": [
                    {
                        "title": _("Campaigns"),
                        "icon": "campaign",
                        "link": lambda request: reverse("admin:marketing_campaign_changelist"),
                    },
                    {
                        "title": _("Customer Segments"),
                        "icon": "segment",
                        "link": lambda request: reverse("admin:marketing_segment_changelist"),
                    },
                ],
            },
            {
                "title": _("Support & FAQ"),
                "separator": True,
                "items": [
                    {
                        "title": _("Tickets"),
                        "icon": "confirmation_number",
                        "link": lambda request: reverse("admin:support_supportticket_changelist"),
                    },
                    {
                        "title": _("FAQs"),
                        "icon": "quiz",
                        "link": lambda request: reverse("admin:support_faq_changelist"),
                    },
                ],
            },
        ],
    },
}
