# Generated by Django 6.0.2 on 2026-03-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_access_advanced_scheduling",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_inventory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_marketing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_memberships",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_packages",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_staff_mgmt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_super_admin",
            field=models.BooleanField(
                default=False, help_text="Bypass all plan restrictions"
            ),
        ),
    ]
