# Generated by Django 6.0.2 on 2026-03-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_userprofile_can_access_advanced_scheduling_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_access_whatsapp",
            field=models.BooleanField(default=False),
        ),
    ]
