# Generated by Django 6.0.2 on 2026-03-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0003_userprofile_can_access_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_access_advanced_security",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_ai_assistant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_analytics",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_api",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_custom_reporting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_dedicated_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_loyalty",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_multi_center",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_onboarding",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_priority_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_promo_campaigns",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_sponsored_ads",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_staff_performance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_access_whitelabel",
            field=models.BooleanField(default=False),
        ),
    ]
