# Generated by Django 6.0.2 on 2026-02-14 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subdomain", models.SlugField(max_length=100, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
                ),
                (
                    "gst_file",
                    models.FileField(
                        blank=True, null=True, upload_to="tenant_docs/gst/"
                    ),
                ),
                (
                    "pan_file",
                    models.FileField(
                        blank=True, null=True, upload_to="tenant_docs/pan/"
                    ),
                ),
                (
                    "business_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="tenant_docs/proof/"
                    ),
                ),
                ("industry_type", models.JSONField(blank=True, default=list)),
                (
                    "clientele_type",
                    models.CharField(
                        choices=[
                            ("UNISEX", "Unisex"),
                            ("MEN", "Men Only"),
                            ("WOMEN", "Women Only"),
                            ("KIDS", "Kids Only"),
                        ],
                        default="UNISEX",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="tenants", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_tenants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
