# Generated by Django 6.0.2 on 2026-03-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="sms_credits",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
