# Generated by Django 6.0.2 on 2026-03-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0002_tenant_sms_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="plan",
            field=models.CharField(
                choices=[
                    ("FREE", "Free"),
                    ("PROFESSIONAL", "Professional"),
                    ("BUSINESS", "Business"),
                    ("ENTERPRISE", "Enterprise"),
                ],
                default="FREE",
                max_length=20,
            ),
        ),
    ]
