# Generated by Django 6.0.2 on 2026-03-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0003_tenant_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_business_account_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_invoice_template",
            field=models.CharField(default="invoice_notification", max_length=100),
        ),
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_phone_number_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
