# Generated by Django 6.0.2 on 2026-03-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experience", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
